POST http://localhost:3000/api/barang HTTP/1.1
content-type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsIiwiZnVsbG5hbWUiOiJGYWtocnkgSGl6IiwiZW1haWwiOiJmYUBhbC5jb20iLCJub3dhIjoiMDg5NTMyMTcwMTc5OCIsImlhdCI6MTc2MDkzMjE3MCwiZXhwIjoxNzYxNTM2OTcwfQ.jY1qCax5pT-wEZYWE3pX0lyAlEURbIWNnbltQ2OTDkQ; selectedTenanId=1

{
    "nama_barang": "Beras 5Kg",
    "jenis_barang": "beras",
    "satuan_besar": "bundel",
    "kapasitas": 5,
    "satuan_kecil": "pcs",
    "harga": 1000
}

###
GET http://localhost:3000/api/barang/ccategory HTTP/1.1
content-type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsIiwiZnVsbG5hbWUiOiJGYWtocnkgSGl6IiwiZW1haWwiOiJmYUBhbC5jb20iLCJub3dhIjoiMDg5NTMyMTcwMTc5OCIsImlhdCI6MTc2MDkzMjE3MCwiZXhwIjoxNzYxNTM2OTcwfQ.jY1qCax5pT-wEZYWE3pX0lyAlEURbIWNnbltQ2OTDkQ; selectedTenanId=1


###
GET http://localhost:3000/api/barang?jenis_barang=1-beras HTTP/1.1
content-type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsIiwiZnVsbG5hbWUiOiJGYWtocnkgSGl6IiwiZW1haWwiOiJmYUBhbC5jb20iLCJub3dhIjoiMDg5NTMyMTcwMTc5OCIsImlhdCI6MTc2MDkzMjE3MCwiZXhwIjoxNzYxNTM2OTcwfQ.jY1qCax5pT-wEZYWE3pX0lyAlEURbIWNnbltQ2OTDkQ; selectedTenanId=1

###
GET http://localhost:3000/api/barang HTTP/1.1
content-type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsIiwiZnVsbG5hbWUiOiJGYWtocnkgSGl6IiwiZW1haWwiOiJmYUBhbC5jb20iLCJub3dhIjoiMDg5NTMyMTcwMTc5OCIsImlhdCI6MTc2MDkzMjE3MCwiZXhwIjoxNzYxNTM2OTcwfQ.jY1qCax5pT-wEZYWE3pX0lyAlEURbIWNnbltQ2OTDkQ; selectedTenanId=1

###
GET http://localhost:3000/api/barang/cari?nama_barang=ber&jenis_barang= HTTP/1.1
content-type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsIiwiZnVsbG5hbWUiOiJGYWtocnkgSGl6IiwiZW1haWwiOiJmYUBhbC5jb20iLCJub3dhIjoiMDg5NTMyMTcwMTc5OCIsImlhdCI6MTc2MDkzMjE3MCwiZXhwIjoxNzYxNTM2OTcwfQ.jY1qCax5pT-wEZYWE3pX0lyAlEURbIWNnbltQ2OTDkQ; selectedTenanId=1

###
POST http://localhost:3000/api/supplier HTTP/1.1
content-type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsIiwiZnVsbG5hbWUiOiJGYWtocnkgSGl6IiwiZW1haWwiOiJmYUBhbC5jb20iLCJub3dhIjoiMDg5NTMyMTcwMTc5OCIsImlhdCI6MTc2MDkzMjE3MCwiZXhwIjoxNzYxNTM2OTcwfQ.jY1qCax5pT-wEZYWE3pX0lyAlEURbIWNnbltQ2OTDkQ; selectedTenanId=1

{
    "supplier": "Pasar Senin",
    "alamat": "-",
    "nowa": "0"
}

###
GET http://localhost:3000/api/supplier HTTP/1.1
content-type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsIiwiZnVsbG5hbWUiOiJGYWtocnkgSGl6IiwiZW1haWwiOiJmYUBhbC5jb20iLCJub3dhIjoiMDg5NTMyMTcwMTc5OCIsImlhdCI6MTc2MDkzMjE3MCwiZXhwIjoxNzYxNTM2OTcwfQ.jY1qCax5pT-wEZYWE3pX0lyAlEURbIWNnbltQ2OTDkQ; selectedTenanId=1

###
PUT http://localhost:3000/api/supplier HTTP/1.1
content-type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsIiwiZnVsbG5hbWUiOiJGYWtocnkgSGl6IiwiZW1haWwiOiJmYUBhbC5jb20iLCJub3dhIjoiMDg5NTMyMTcwMTc5OCIsImlhdCI6MTc2MDkzMjE3MCwiZXhwIjoxNzYxNTM2OTcwfQ.jY1qCax5pT-wEZYWE3pX0lyAlEURbIWNnbltQ2OTDkQ; selectedTenanId=1

{
    "id":1,
    "supplier": "Belanja Mandri",
    "alamat": "-",
    "nowa": "0"
}

###
DELETE http://localhost:3000/api/supplier HTTP/1.1
content-type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsIiwiZnVsbG5hbWUiOiJGYWtocnkgSGl6IiwiZW1haWwiOiJmYUBhbC5jb20iLCJub3dhIjoiMDg5NTMyMTcwMTc5OCIsImlhdCI6MTc2MDkzMjE3MCwiZXhwIjoxNzYxNTM2OTcwfQ.jY1qCax5pT-wEZYWE3pX0lyAlEURbIWNnbltQ2OTDkQ; selectedTenanId=1

{
    "kode_supplier":2
}

###
GET http://localhost:3000/api/gudang HTTP/1.1
content-type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsIiwiZnVsbG5hbWUiOiJGYWtocnkgSGl6IiwiZW1haWwiOiJmYUBhbC5jb20iLCJub3dhIjoiMDg5NTMyMTcwMTc5OCIsImlhdCI6MTc2MDkzMjE3MCwiZXhwIjoxNzYxNTM2OTcwfQ.jY1qCax5pT-wEZYWE3pX0lyAlEURbIWNnbltQ2OTDkQ; selectedTenanId=1


###
POST http://localhost:3000/api/gudang HTTP/1.1
content-type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsIiwiZnVsbG5hbWUiOiJGYWtocnkgSGl6IiwiZW1haWwiOiJmYUBhbC5jb20iLCJub3dhIjoiMDg5NTMyMTcwMTc5OCIsImlhdCI6MTc2MDkzMjE3MCwiZXhwIjoxNzYxNTM2OTcwfQ.jY1qCax5pT-wEZYWE3pX0lyAlEURbIWNnbltQ2OTDkQ; selectedTenanId=1

{
    "depo":"Dapur"
}

### find Depo
GET http://localhost:3000/api/gudang/stokall/1-dapur HTTP/1.1
content-type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsIiwiZnVsbG5hbWUiOiJGYWtocnkgSGl6IiwiZW1haWwiOiJmYUBhbC5jb20iLCJub3dhIjoiMDg5NTMyMTcwMTc5OCIsImlhdCI6MTc2MDkzMjE3MCwiZXhwIjoxNzYxNTM2OTcwfQ.jY1qCax5pT-wEZYWE3pX0lyAlEURbIWNnbltQ2OTDkQ; selectedTenanId=1

###
GET http://localhost:3000/api/gudang/stok/1-dapur?nama_barang=ap HTTP/1.1
content-type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsIiwiZnVsbG5hbWUiOiJGYWtocnkgSGl6IiwiZW1haWwiOiJmYUBhbC5jb20iLCJub3dhIjoiMDg5NTMyMTcwMTc5OCIsImlhdCI6MTc2MDkzMjE3MCwiZXhwIjoxNzYxNTM2OTcwfQ.jY1qCax5pT-wEZYWE3pX0lyAlEURbIWNnbltQ2OTDkQ; selectedTenanId=1

###
POST http://localhost:3000/api/gudang/stokOpname/1-dapur HTTP/1.1
content-type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsIiwiZnVsbG5hbWUiOiJGYWtocnkgSGl6IiwiZW1haWwiOiJmYUBhbC5jb20iLCJub3dhIjoiMDg5NTMyMTcwMTc5OCIsImlhdCI6MTc2MDkzMjE3MCwiZXhwIjoxNzYxNTM2OTcwfQ.jY1qCax5pT-wEZYWE3pX0lyAlEURbIWNnbltQ2OTDkQ; selectedTenanId=1

