POST http://localhost:3000/api/barang HTTP/1.1
content-type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsIiwiZnVsbG5hbWUiOiJGYWtocnkgSGl6IiwiZW1haWwiOiJmYUBhbC5jb20iLCJub3dhIjoiMDg5NTMyMTcwMTc5OCIsImlhdCI6MTc1OTY1NzgwMywiZXhwIjoxNzYwMjYyNjAzfQ.Hk_0-fKn66xx65vHlWFKxjbNcvKc41FIKwqC5sau5Bk; selectedTenanId=1

{
    "nama_barang": "AC",
    "jenis_barang": "Lainnya",
    "satuan_besar": "box",
    "kapasitas": 100,
    "satuan_kecil": "pcs",
    "harga": 1000
}
###